# Site settings
title: Notes Toward A More Inclusive Syllabus
tag_text: Notes Toward A More Inclusive Syllabus
description: Overview of rethinking my syllabus.
url: "https://jloan.github.io/inclusive_syllabi/"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
